### PR TITLE
Fixing renaming and deletion issues

### PR DESCRIPTION
**Pull request by falkzilm**

### CODE REVIEW

**Comment by rodriguezsergio** [comment]
Is there a chance this will get a look? @rodrigc

**Comment by zjkyz8** [comment]
any update for this issue?

**Comment by boonware** [comment]
Any update on this? The plugin is practically unusable now due to the problems with renaming and deleting jobs.

**Comment by rodriguezsergio** [comment]
@boonware I couldn't wait to get a backup script into production, so I took this and tweaked it a bit to my needs.

https://gist.github.com/cenk/5089392

**Comment by pupssman** [comment]
Hey, folks!
Anyone looking at this? 
I might lend a hand in fixing/merging this as I need that myself a lot.

**Comment by Darthholi** [comment]
Please do repair this

**Comment by oberones** [comment]
+1 for merging this PR.

**Comment by laapsaap** [comment]
For crying out loud, the plugin is completely unusable without this fix. Lets get this going.. Look at the dates..

**Comment by Darthholi** [comment]
To everybody who needs jenkins configuration saving to SCM - I did my own job, that saves things like this:

(robocmd is robocopy, JenkinsHome is programfiles/jenkins, MedBuildHome is SCM repository)

```
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}"\\jobs ${MedBuildHome}\\Jenkins\\jobs *config.xml /S /ZB /PURGE ${LogoutputParams} ${ExcludeParams}
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}"\\users ${MedBuildHome}\\Jenkins\\users *config.xml /S /ZB /PURGE ${LogoutputParams} ${ExcludeParams}
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}" ${MedBuildHome}\\Jenkins *config.xml /ZB /PURGE ${LogoutputParams} ${ExcludeParams}
          
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}" ${MedBuildHome}\\Jenkins *hudson*.xml /ZB /PURGE ${LogoutputParams} ${ExcludeParams}
                                                     
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}" ${MedBuildHome}\\Jenkins *.groovy /S /ZB /PURGE ${LogoutputParams} ${ExcludeParams}
          
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}" ${MedBuildHome}\\Jenkins *.ppr /ZB /PURGE ${LogoutputParams} ${ExcludeParams}
          
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}" ${MedBuildHome}\\Jenkins *.reg /ZB /PURGE ${LogoutputParams} ${ExcludeParams}
          
          call ${BuildTools}\\robocmd.bat "${JenkinsHome}" ${MedBuildHome}\\Jenkins *logparser.txt /ZB /PURGE ${LogoutputParams} ${ExcludeParams} 
                    
          git -C "${MedBuildHome}" add -A
          git -C "${MedBuildHome}" commit -m "${Msg}"
          git -C "${MedBuildHome}" push origin  
```

**Comment by vkruoso** [comment]
Looks like the project maintainers are not around for a while now. Is there any alternatives to this plugin that are actually being maintained works for deleting jobs?

**Comment by vzabauski** [comment]
Any updates?

**Comment by boonware** [comment]
I have stopped using this plug-in due to the issue at hand but also down to the fact that this plug-in does not peform a full backup. To fully back up Jenkins one needs to copy the entire JENKINS_HOME directory. I would advise to do the same.

**Comment by vzabauski** [comment]
Well, this plugin is not that bad, I've restored once Jenkins from it and it almost worked out of the box but yes, it's definitely not flawless.
A good option is to try to build a custom version of this plugin with all patches provided by community applied since this repo seems to be abandoned.

**Comment by sharksforarms** [comment]
any updates???

**Comment by yuchaoran2011** [comment]
This issue should NOT be closed @guipal. A guy in the comment of this [page](https://issues.jenkins-ci.org/browse/JENKINS-15128) reported facing the issue still. Today I ran into the same problem.

**Comment by guipal** [comment]
This is not an issue but a pull request from another user. It was closed
because it was merged nevertheless those is not still being distributed as
I'm waiting to include few more features before releasing a new version. If
you want this feature just checkout the repo and build
It yourself.

Cheers

**Pull request closed without merging**
