### PR TITLE
Avoid failing when delete or rename a branch

### PR DESCRIPTION
**Pull request by mnencia**
The content of #38 has been rebased on current master, it should fix #32 #37 and JENKINS-37500

I've cleaned up the commits from the previous pull requests and added one to prevent the SCM manager to delete any path that doesn't exists in the repository.

### CODE REVIEW

**Comment by j-martin** [comment]
This PR is a big deal for us since we are using Jenkins Pipeline with the Github Organization Plugin which creates and deletes nested jobs constantly.

Thanks for your work!

**Comment by daubman** [comment]
We'd love to see this fix as well, it seems inconsistent but we seem to hit this occasionally even when just deleting "normal" jobs...

**Comment by marcolenzo** [comment]
I am honestly baffled that such an issue has been discussed from over an year on #32 and it has never seen official feedback from the repository admins. This is a blocker issue that needs to be fixed otherwise the plugin is totally useless.

**Comment by mnencia** [comment]
I think that the right place to complain is the JIRA issue https://issues.jenkins-ci.org/browse/JENKINS-37500

**Comment by pupssman** [comment]
@rodrigc hi! Is there a chance for this PR to be merged and released any time soon?

**Comment by shraykay** [comment]
@rodrigc bump! would really like to add this fix

**Comment by erikhakansson** [comment]
@rodrigc +1 from me. I have to do the manual workaround daily now.

Is this plugin abandoned? Perhaps you could give it up for adoption.

**Comment by xocasdashdash** [comment]
@rodrigc any eta on this getting merged anytime soon?

**Comment by hogarthj** [comment]
@erikhakansson if it's a help for you i've compiled this plugin with the PR applied here:

https://purley.hogarthuk.com/scm-sync-configuration.hpi

replace it with the official one when there's eventually a release of course

**Comment by cpoole** [comment]
Friendly bump. Without this merge this plugin is DOA for any new jenkins projects

**Comment by j-martin** [comment]
Bumping again, confirming this solved our problem and has been working great for use for the past 4 months.

**Comment by incedo** [comment]
I was wondering why this hasn't been merged yet? We would like to use the multibranch plugin in our current environment that is using the scm sync plugin. If there is something that needs to be done please let us know

**Comment by mnencia** [comment]
The issue is explained in #54
This plugin is orphan, so no one will merge it, unless a new maintainer will arise.

**Comment by giladsh1** [comment]
@hogarthj thanks a lot!

in order to fix this issue, you can use the following workaround - 
- compile your own version of the plugin from this PR (or use @hogarthj version above)
- stop jenkins master service
- go to $JENKINS_HOME/plugins
-  Remove the previously expanded plugin directory
- Copy the custom HPI file to $JENKINS_HOME/plugins
- touch <plugin>.hpi.pinned
- restart your jenkins master

more details on using custom plugin versions here - 
https://wiki.jenkins.io/display/JENKINS/Plugin+tutorial

**Comment by sharksforarms** [comment]
any updates on getting this merged

**Comment by mnencia** [comment]
I have the strong feeling that this plugin is abandoned and this patch will never be merged. I've personally stopped using it in favour of generating the configuration through jenkins-job-builder

**Comment by sharksforarms** [comment]
@guipal Thanks for looking at this! Hopefully a release can be pushed and bring this plugin back to glory!

@mnencia Merged!

**Comment by clintharrison** [comment]
@guipal as you have taken ownership of this plugin, are you able to release a new version now that this has been merged?

**Pull request merged**
